/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiWatchdogRouteImport } from './routes/_authenticated/ai-watchdog'
import { Route as AuthenticatedAllocationDeliveryPlanRouteImport } from './routes/_authenticated/allocation-delivery-plan'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCreditInventoryPurchasesRouteImport } from './routes/_authenticated/credit-inventory-purchases'
import { Route as AuthenticatedCustomerAnalyticsRouteImport } from './routes/_authenticated/customer-analytics'
import { Route as AuthenticatedCustomerLedgerRouteImport } from './routes/_authenticated/customer-ledger'
import { Route as AuthenticatedEmployeePerformanceRouteImport } from './routes/_authenticated/employee-performance'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedInvestorLeadsRouteImport } from './routes/_authenticated/investor-leads'
import { Route as AuthenticatedOperationalAlertsRouteImport } from './routes/_authenticated/operational-alerts'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPaymentRemindersRouteImport } from './routes/_authenticated/payment-reminders'
import { Route as AuthenticatedPaymentVerificationsRouteImport } from './routes/_authenticated/payment-verifications'
import { Route as AuthenticatedPnlRouteImport } from './routes/_authenticated/pnl'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProductionPlanningRouteImport } from './routes/_authenticated/production-planning'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedSalariesRouteImport } from './routes/_authenticated/salaries'
import { Route as AuthenticatedSalesLeadsRouteImport } from './routes/_authenticated/sales-leads'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStockAuditsRouteImport } from './routes/_authenticated/stock-audits'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWastageVerificationsRouteImport } from './routes/_authenticated/wastage-verifications'
import { Route as AuthenticatedWhatsappLogsRouteImport } from './routes/_authenticated/whatsapp-logs'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalLedgerRouteImport } from './routes/portal/ledger'
import { Route as PortalOrdersRouteImport } from './routes/portal/orders'
import { Route as AuthenticatedInvestorsIndexRouteImport } from './routes/_authenticated/investors.index'
import { Route as AuthenticatedInvestorsIdRouteImport } from './routes/_authenticated/investors.$id'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesDeletedRouteImport } from './routes/_authenticated/invoices.deleted'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiWatchdogRoute = AuthenticatedAiWatchdogRouteImport.update({
  id: '/ai-watchdog',
  path: '/ai-watchdog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAllocationDeliveryPlanRoute =
  AuthenticatedAllocationDeliveryPlanRouteImport.update({
    id: '/allocation-delivery-plan',
    path: '/allocation-delivery-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditInventoryPurchasesRoute =
  AuthenticatedCreditInventoryPurchasesRouteImport.update({
    id: '/credit-inventory-purchases',
    path: '/credit-inventory-purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerAnalyticsRoute =
  AuthenticatedCustomerAnalyticsRouteImport.update({
    id: '/customer-analytics',
    path: '/customer-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomerLedgerRoute =
  AuthenticatedCustomerLedgerRouteImport.update({
    id: '/customer-ledger',
    path: '/customer-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeePerformanceRoute =
  AuthenticatedEmployeePerformanceRouteImport.update({
    id: '/employee-performance',
    path: '/employee-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorLeadsRoute =
  AuthenticatedInvestorLeadsRouteImport.update({
    id: '/investor-leads',
    path: '/investor-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationalAlertsRoute =
  AuthenticatedOperationalAlertsRouteImport.update({
    id: '/operational-alerts',
    path: '/operational-alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentRemindersRoute =
  AuthenticatedPaymentRemindersRouteImport.update({
    id: '/payment-reminders',
    path: '/payment-reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentVerificationsRoute =
  AuthenticatedPaymentVerificationsRouteImport.update({
    id: '/payment-verifications',
    path: '/payment-verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPnlRoute = AuthenticatedPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionPlanningRoute =
  AuthenticatedProductionPlanningRouteImport.update({
    id: '/production-planning',
    path: '/production-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalariesRoute = AuthenticatedSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesLeadsRoute = AuthenticatedSalesLeadsRouteImport.update({
  id: '/sales-leads',
  path: '/sales-leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockAuditsRoute =
  AuthenticatedStockAuditsRouteImport.update({
    id: '/stock-audits',
    path: '/stock-audits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWastageVerificationsRoute =
  AuthenticatedWastageVerificationsRouteImport.update({
    id: '/wastage-verifications',
    path: '/wastage-verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappLogsRoute =
  AuthenticatedWhatsappLogsRouteImport.update({
    id: '/whatsapp-logs',
    path: '/whatsapp-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLedgerRoute = PortalLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedInvestorsIndexRoute =
  AuthenticatedInvestorsIndexRouteImport.update({
    id: '/investors/',
    path: '/investors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestorsIdRoute =
  AuthenticatedInvestorsIdRouteImport.update({
    id: '/investors/$id',
    path: '/investors/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesDeletedRoute =
  AuthenticatedInvoicesDeletedRouteImport.update({
    id: '/invoices/deleted',
    path: '/invoices/deleted',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/invest': typeof InvestRoute
  '/portal': typeof PortalRouteWithChildren
  '/trust': typeof TrustRoute
  '/ai-watchdog': typeof AuthenticatedAiWatchdogRoute
  '/allocation-delivery-plan': typeof AuthenticatedAllocationDeliveryPlanRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit-inventory-purchases': typeof AuthenticatedCreditInventoryPurchasesRoute
  '/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/customer-ledger': typeof AuthenticatedCustomerLedgerRoute
  '/employee-performance': typeof AuthenticatedEmployeePerformanceRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/investor-leads': typeof AuthenticatedInvestorLeadsRoute
  '/operational-alerts': typeof AuthenticatedOperationalAlertsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/payment-verifications': typeof AuthenticatedPaymentVerificationsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/sales-leads': typeof AuthenticatedSalesLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-audits': typeof AuthenticatedStockAuditsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/wastage-verifications': typeof AuthenticatedWastageVerificationsRoute
  '/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/': typeof PortalIndexRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/invest': typeof InvestRoute
  '/trust': typeof TrustRoute
  '/ai-watchdog': typeof AuthenticatedAiWatchdogRoute
  '/allocation-delivery-plan': typeof AuthenticatedAllocationDeliveryPlanRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit-inventory-purchases': typeof AuthenticatedCreditInventoryPurchasesRoute
  '/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/customer-ledger': typeof AuthenticatedCustomerLedgerRoute
  '/employee-performance': typeof AuthenticatedEmployeePerformanceRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/investor-leads': typeof AuthenticatedInvestorLeadsRoute
  '/operational-alerts': typeof AuthenticatedOperationalAlertsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/payment-verifications': typeof AuthenticatedPaymentVerificationsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/sales-leads': typeof AuthenticatedSalesLeadsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock-audits': typeof AuthenticatedStockAuditsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/wastage-verifications': typeof AuthenticatedWastageVerificationsRoute
  '/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/': typeof AuthenticatedIndexRoute
  '/portal': typeof PortalIndexRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/investors': typeof AuthenticatedInvestorsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/invest': typeof InvestRoute
  '/portal': typeof PortalRouteWithChildren
  '/trust': typeof TrustRoute
  '/_authenticated/ai-watchdog': typeof AuthenticatedAiWatchdogRoute
  '/_authenticated/allocation-delivery-plan': typeof AuthenticatedAllocationDeliveryPlanRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/credit-inventory-purchases': typeof AuthenticatedCreditInventoryPurchasesRoute
  '/_authenticated/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/_authenticated/customer-ledger': typeof AuthenticatedCustomerLedgerRoute
  '/_authenticated/employee-performance': typeof AuthenticatedEmployeePerformanceRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/investor-leads': typeof AuthenticatedInvestorLeadsRoute
  '/_authenticated/operational-alerts': typeof AuthenticatedOperationalAlertsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payment-reminders': typeof AuthenticatedPaymentRemindersRoute
  '/_authenticated/payment-verifications': typeof AuthenticatedPaymentVerificationsRoute
  '/_authenticated/pnl': typeof AuthenticatedPnlRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-planning': typeof AuthenticatedProductionPlanningRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/salaries': typeof AuthenticatedSalariesRoute
  '/_authenticated/sales-leads': typeof AuthenticatedSalesLeadsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock-audits': typeof AuthenticatedStockAuditsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/wastage-verifications': typeof AuthenticatedWastageVerificationsRoute
  '/_authenticated/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/portal/ledger': typeof PortalLedgerRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/_authenticated/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/_authenticated/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/invest'
    | '/portal'
    | '/trust'
    | '/ai-watchdog'
    | '/allocation-delivery-plan'
    | '/clients'
    | '/credit-inventory-purchases'
    | '/customer-analytics'
    | '/customer-ledger'
    | '/employee-performance'
    | '/expenses'
    | '/inventory'
    | '/investor'
    | '/investor-leads'
    | '/operational-alerts'
    | '/orders'
    | '/payment-reminders'
    | '/payment-verifications'
    | '/pnl'
    | '/production'
    | '/production-planning'
    | '/returns'
    | '/salaries'
    | '/sales-leads'
    | '/settings'
    | '/stock-audits'
    | '/today'
    | '/wastage-verifications'
    | '/whatsapp-logs'
    | '/portal/ledger'
    | '/portal/orders'
    | '/portal/'
    | '/investors/$id'
    | '/invoices/deleted'
    | '/investors/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/invest'
    | '/trust'
    | '/ai-watchdog'
    | '/allocation-delivery-plan'
    | '/clients'
    | '/credit-inventory-purchases'
    | '/customer-analytics'
    | '/customer-ledger'
    | '/employee-performance'
    | '/expenses'
    | '/inventory'
    | '/investor'
    | '/investor-leads'
    | '/operational-alerts'
    | '/orders'
    | '/payment-reminders'
    | '/payment-verifications'
    | '/pnl'
    | '/production'
    | '/production-planning'
    | '/returns'
    | '/salaries'
    | '/sales-leads'
    | '/settings'
    | '/stock-audits'
    | '/today'
    | '/wastage-verifications'
    | '/whatsapp-logs'
    | '/portal/ledger'
    | '/portal/orders'
    | '/'
    | '/portal'
    | '/investors/$id'
    | '/invoices/deleted'
    | '/investors'
    | '/invoices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/invest'
    | '/portal'
    | '/trust'
    | '/_authenticated/ai-watchdog'
    | '/_authenticated/allocation-delivery-plan'
    | '/_authenticated/clients'
    | '/_authenticated/credit-inventory-purchases'
    | '/_authenticated/customer-analytics'
    | '/_authenticated/customer-ledger'
    | '/_authenticated/employee-performance'
    | '/_authenticated/expenses'
    | '/_authenticated/inventory'
    | '/_authenticated/investor'
    | '/_authenticated/investor-leads'
    | '/_authenticated/operational-alerts'
    | '/_authenticated/orders'
    | '/_authenticated/payment-reminders'
    | '/_authenticated/payment-verifications'
    | '/_authenticated/pnl'
    | '/_authenticated/production'
    | '/_authenticated/production-planning'
    | '/_authenticated/returns'
    | '/_authenticated/salaries'
    | '/_authenticated/sales-leads'
    | '/_authenticated/settings'
    | '/_authenticated/stock-audits'
    | '/_authenticated/today'
    | '/_authenticated/wastage-verifications'
    | '/_authenticated/whatsapp-logs'
    | '/portal/ledger'
    | '/portal/orders'
    | '/_authenticated/'
    | '/portal/'
    | '/_authenticated/investors/$id'
    | '/_authenticated/invoices/deleted'
    | '/_authenticated/investors/'
    | '/_authenticated/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InvestRoute: typeof InvestRoute
  PortalRoute: typeof PortalRouteWithChildren
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-watchdog': {
      id: '/_authenticated/ai-watchdog'
      path: '/ai-watchdog'
      fullPath: '/ai-watchdog'
      preLoaderRoute: typeof AuthenticatedAiWatchdogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allocation-delivery-plan': {
      id: '/_authenticated/allocation-delivery-plan'
      path: '/allocation-delivery-plan'
      fullPath: '/allocation-delivery-plan'
      preLoaderRoute: typeof AuthenticatedAllocationDeliveryPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit-inventory-purchases': {
      id: '/_authenticated/credit-inventory-purchases'
      path: '/credit-inventory-purchases'
      fullPath: '/credit-inventory-purchases'
      preLoaderRoute: typeof AuthenticatedCreditInventoryPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-analytics': {
      id: '/_authenticated/customer-analytics'
      path: '/customer-analytics'
      fullPath: '/customer-analytics'
      preLoaderRoute: typeof AuthenticatedCustomerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-ledger': {
      id: '/_authenticated/customer-ledger'
      path: '/customer-ledger'
      fullPath: '/customer-ledger'
      preLoaderRoute: typeof AuthenticatedCustomerLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-performance': {
      id: '/_authenticated/employee-performance'
      path: '/employee-performance'
      fullPath: '/employee-performance'
      preLoaderRoute: typeof AuthenticatedEmployeePerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor-leads': {
      id: '/_authenticated/investor-leads'
      path: '/investor-leads'
      fullPath: '/investor-leads'
      preLoaderRoute: typeof AuthenticatedInvestorLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operational-alerts': {
      id: '/_authenticated/operational-alerts'
      path: '/operational-alerts'
      fullPath: '/operational-alerts'
      preLoaderRoute: typeof AuthenticatedOperationalAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-reminders': {
      id: '/_authenticated/payment-reminders'
      path: '/payment-reminders'
      fullPath: '/payment-reminders'
      preLoaderRoute: typeof AuthenticatedPaymentRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-verifications': {
      id: '/_authenticated/payment-verifications'
      path: '/payment-verifications'
      fullPath: '/payment-verifications'
      preLoaderRoute: typeof AuthenticatedPaymentVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pnl': {
      id: '/_authenticated/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof AuthenticatedPnlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-planning': {
      id: '/_authenticated/production-planning'
      path: '/production-planning'
      fullPath: '/production-planning'
      preLoaderRoute: typeof AuthenticatedProductionPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salaries': {
      id: '/_authenticated/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof AuthenticatedSalariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-leads': {
      id: '/_authenticated/sales-leads'
      path: '/sales-leads'
      fullPath: '/sales-leads'
      preLoaderRoute: typeof AuthenticatedSalesLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-audits': {
      id: '/_authenticated/stock-audits'
      path: '/stock-audits'
      fullPath: '/stock-audits'
      preLoaderRoute: typeof AuthenticatedStockAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wastage-verifications': {
      id: '/_authenticated/wastage-verifications'
      path: '/wastage-verifications'
      fullPath: '/wastage-verifications'
      preLoaderRoute: typeof AuthenticatedWastageVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-logs': {
      id: '/_authenticated/whatsapp-logs'
      path: '/whatsapp-logs'
      fullPath: '/whatsapp-logs'
      preLoaderRoute: typeof AuthenticatedWhatsappLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ledger': {
      id: '/portal/ledger'
      path: '/ledger'
      fullPath: '/portal/ledger'
      preLoaderRoute: typeof PortalLedgerRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/investors/': {
      id: '/_authenticated/investors/'
      path: '/investors'
      fullPath: '/investors/'
      preLoaderRoute: typeof AuthenticatedInvestorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investors/$id': {
      id: '/_authenticated/investors/$id'
      path: '/investors/$id'
      fullPath: '/investors/$id'
      preLoaderRoute: typeof AuthenticatedInvestorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/deleted': {
      id: '/_authenticated/invoices/deleted'
      path: '/invoices/deleted'
      fullPath: '/invoices/deleted'
      preLoaderRoute: typeof AuthenticatedInvoicesDeletedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiWatchdogRoute: typeof AuthenticatedAiWatchdogRoute
  AuthenticatedAllocationDeliveryPlanRoute: typeof AuthenticatedAllocationDeliveryPlanRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCreditInventoryPurchasesRoute: typeof AuthenticatedCreditInventoryPurchasesRoute
  AuthenticatedCustomerAnalyticsRoute: typeof AuthenticatedCustomerAnalyticsRoute
  AuthenticatedCustomerLedgerRoute: typeof AuthenticatedCustomerLedgerRoute
  AuthenticatedEmployeePerformanceRoute: typeof AuthenticatedEmployeePerformanceRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedInvestorLeadsRoute: typeof AuthenticatedInvestorLeadsRoute
  AuthenticatedOperationalAlertsRoute: typeof AuthenticatedOperationalAlertsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPaymentRemindersRoute: typeof AuthenticatedPaymentRemindersRoute
  AuthenticatedPaymentVerificationsRoute: typeof AuthenticatedPaymentVerificationsRoute
  AuthenticatedPnlRoute: typeof AuthenticatedPnlRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionPlanningRoute: typeof AuthenticatedProductionPlanningRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedSalariesRoute: typeof AuthenticatedSalariesRoute
  AuthenticatedSalesLeadsRoute: typeof AuthenticatedSalesLeadsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockAuditsRoute: typeof AuthenticatedStockAuditsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWastageVerificationsRoute: typeof AuthenticatedWastageVerificationsRoute
  AuthenticatedWhatsappLogsRoute: typeof AuthenticatedWhatsappLogsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInvestorsIdRoute: typeof AuthenticatedInvestorsIdRoute
  AuthenticatedInvoicesDeletedRoute: typeof AuthenticatedInvoicesDeletedRoute
  AuthenticatedInvestorsIndexRoute: typeof AuthenticatedInvestorsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiWatchdogRoute: AuthenticatedAiWatchdogRoute,
  AuthenticatedAllocationDeliveryPlanRoute:
    AuthenticatedAllocationDeliveryPlanRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCreditInventoryPurchasesRoute:
    AuthenticatedCreditInventoryPurchasesRoute,
  AuthenticatedCustomerAnalyticsRoute: AuthenticatedCustomerAnalyticsRoute,
  AuthenticatedCustomerLedgerRoute: AuthenticatedCustomerLedgerRoute,
  AuthenticatedEmployeePerformanceRoute: AuthenticatedEmployeePerformanceRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedInvestorLeadsRoute: AuthenticatedInvestorLeadsRoute,
  AuthenticatedOperationalAlertsRoute: AuthenticatedOperationalAlertsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPaymentRemindersRoute: AuthenticatedPaymentRemindersRoute,
  AuthenticatedPaymentVerificationsRoute:
    AuthenticatedPaymentVerificationsRoute,
  AuthenticatedPnlRoute: AuthenticatedPnlRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionPlanningRoute: AuthenticatedProductionPlanningRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedSalariesRoute: AuthenticatedSalariesRoute,
  AuthenticatedSalesLeadsRoute: AuthenticatedSalesLeadsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockAuditsRoute: AuthenticatedStockAuditsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWastageVerificationsRoute:
    AuthenticatedWastageVerificationsRoute,
  AuthenticatedWhatsappLogsRoute: AuthenticatedWhatsappLogsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInvestorsIdRoute: AuthenticatedInvestorsIdRoute,
  AuthenticatedInvoicesDeletedRoute: AuthenticatedInvoicesDeletedRoute,
  AuthenticatedInvestorsIndexRoute: AuthenticatedInvestorsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteChildren {
  PortalLedgerRoute: typeof PortalLedgerRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLedgerRoute: PortalLedgerRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InvestRoute: InvestRoute,
  PortalRoute: PortalRouteWithChildren,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
