/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCustomerAnalyticsRouteImport } from './routes/_authenticated/customer-analytics'
import { Route as AuthenticatedDeliveryCalculatorRouteImport } from './routes/_authenticated/delivery-calculator'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedPnlRouteImport } from './routes/_authenticated/pnl'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedSalariesRouteImport } from './routes/_authenticated/salaries'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWhatsappLogsRouteImport } from './routes/_authenticated/whatsapp-logs'
import { Route as AuthenticatedInvestorsIndexRouteImport } from './routes/_authenticated/investors.index'
import { Route as AuthenticatedInvestorsIdRouteImport } from './routes/_authenticated/investors.$id'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesDeletedRouteImport } from './routes/_authenticated/invoices.deleted'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerAnalyticsRoute =
  AuthenticatedCustomerAnalyticsRouteImport.update({
    id: '/customer-analytics',
    path: '/customer-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryCalculatorRoute =
  AuthenticatedDeliveryCalculatorRouteImport.update({
    id: '/delivery-calculator',
    path: '/delivery-calculator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPnlRoute = AuthenticatedPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalariesRoute = AuthenticatedSalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappLogsRoute =
  AuthenticatedWhatsappLogsRouteImport.update({
    id: '/whatsapp-logs',
    path: '/whatsapp-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestorsIndexRoute =
  AuthenticatedInvestorsIndexRouteImport.update({
    id: '/investors/',
    path: '/investors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestorsIdRoute =
  AuthenticatedInvestorsIdRouteImport.update({
    id: '/investors/$id',
    path: '/investors/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesDeletedRoute =
  AuthenticatedInvoicesDeletedRouteImport.update({
    id: '/invoices/deleted',
    path: '/invoices/deleted',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/delivery-calculator': typeof AuthenticatedDeliveryCalculatorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/production': typeof AuthenticatedProductionRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/delivery-calculator': typeof AuthenticatedDeliveryCalculatorRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/production': typeof AuthenticatedProductionRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/salaries': typeof AuthenticatedSalariesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/': typeof AuthenticatedIndexRoute
  '/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/investors': typeof AuthenticatedInvestorsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/customer-analytics': typeof AuthenticatedCustomerAnalyticsRoute
  '/_authenticated/delivery-calculator': typeof AuthenticatedDeliveryCalculatorRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/pnl': typeof AuthenticatedPnlRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/salaries': typeof AuthenticatedSalariesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whatsapp-logs': typeof AuthenticatedWhatsappLogsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/investors/$id': typeof AuthenticatedInvestorsIdRoute
  '/_authenticated/invoices/deleted': typeof AuthenticatedInvoicesDeletedRoute
  '/_authenticated/investors/': typeof AuthenticatedInvestorsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trust'
    | '/clients'
    | '/customer-analytics'
    | '/delivery-calculator'
    | '/expenses'
    | '/inventory'
    | '/investor'
    | '/pnl'
    | '/production'
    | '/returns'
    | '/salaries'
    | '/settings'
    | '/whatsapp-logs'
    | '/investors/$id'
    | '/invoices/deleted'
    | '/investors/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/trust'
    | '/clients'
    | '/customer-analytics'
    | '/delivery-calculator'
    | '/expenses'
    | '/inventory'
    | '/investor'
    | '/pnl'
    | '/production'
    | '/returns'
    | '/salaries'
    | '/settings'
    | '/whatsapp-logs'
    | '/'
    | '/investors/$id'
    | '/invoices/deleted'
    | '/investors'
    | '/invoices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/trust'
    | '/_authenticated/clients'
    | '/_authenticated/customer-analytics'
    | '/_authenticated/delivery-calculator'
    | '/_authenticated/expenses'
    | '/_authenticated/inventory'
    | '/_authenticated/investor'
    | '/_authenticated/pnl'
    | '/_authenticated/production'
    | '/_authenticated/returns'
    | '/_authenticated/salaries'
    | '/_authenticated/settings'
    | '/_authenticated/whatsapp-logs'
    | '/_authenticated/'
    | '/_authenticated/investors/$id'
    | '/_authenticated/invoices/deleted'
    | '/_authenticated/investors/'
    | '/_authenticated/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-analytics': {
      id: '/_authenticated/customer-analytics'
      path: '/customer-analytics'
      fullPath: '/customer-analytics'
      preLoaderRoute: typeof AuthenticatedCustomerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-calculator': {
      id: '/_authenticated/delivery-calculator'
      path: '/delivery-calculator'
      fullPath: '/delivery-calculator'
      preLoaderRoute: typeof AuthenticatedDeliveryCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pnl': {
      id: '/_authenticated/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof AuthenticatedPnlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salaries': {
      id: '/_authenticated/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof AuthenticatedSalariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-logs': {
      id: '/_authenticated/whatsapp-logs'
      path: '/whatsapp-logs'
      fullPath: '/whatsapp-logs'
      preLoaderRoute: typeof AuthenticatedWhatsappLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investors/': {
      id: '/_authenticated/investors/'
      path: '/investors'
      fullPath: '/investors/'
      preLoaderRoute: typeof AuthenticatedInvestorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investors/$id': {
      id: '/_authenticated/investors/$id'
      path: '/investors/$id'
      fullPath: '/investors/$id'
      preLoaderRoute: typeof AuthenticatedInvestorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/deleted': {
      id: '/_authenticated/invoices/deleted'
      path: '/invoices/deleted'
      fullPath: '/invoices/deleted'
      preLoaderRoute: typeof AuthenticatedInvoicesDeletedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCustomerAnalyticsRoute: typeof AuthenticatedCustomerAnalyticsRoute
  AuthenticatedDeliveryCalculatorRoute: typeof AuthenticatedDeliveryCalculatorRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedPnlRoute: typeof AuthenticatedPnlRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedSalariesRoute: typeof AuthenticatedSalariesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsappLogsRoute: typeof AuthenticatedWhatsappLogsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInvestorsIdRoute: typeof AuthenticatedInvestorsIdRoute
  AuthenticatedInvoicesDeletedRoute: typeof AuthenticatedInvoicesDeletedRoute
  AuthenticatedInvestorsIndexRoute: typeof AuthenticatedInvestorsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCustomerAnalyticsRoute: AuthenticatedCustomerAnalyticsRoute,
  AuthenticatedDeliveryCalculatorRoute: AuthenticatedDeliveryCalculatorRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedPnlRoute: AuthenticatedPnlRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedSalariesRoute: AuthenticatedSalariesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsappLogsRoute: AuthenticatedWhatsappLogsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInvestorsIdRoute: AuthenticatedInvestorsIdRoute,
  AuthenticatedInvoicesDeletedRoute: AuthenticatedInvoicesDeletedRoute,
  AuthenticatedInvestorsIndexRoute: AuthenticatedInvestorsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
